In [2]:
from keras.datasets import imdb
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras.models import Sequential
from keras.layers import Embedding, LSTM, Dense,Flatten

In [3]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step


In [4]:
y_test

array([0, 1, 1, ..., 0, 0, 0])

In [5]:
y_train

array([1, 0, 0, ..., 0, 1, 0])

In [6]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [7]:
X_train.shape

(25000, 50)

In [8]:
model = Sequential()
model.add(Embedding(10000,output_dim=1,input_length=50))
model.add(LSTM(32,return_sequences=False))
model.add(Dense(1,activation='sigmoid'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [9]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm (LSTM)                          │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [10]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.fit(X_train,y_train,epochs=5,batch_size=128,validation_data=(X_test,y_test))

Epoch 1/5
196/196 ━━━━━━━━━━━━━━━━━━━━ 8s 14ms/step - accuracy: 0.5688 - loss: 0.6657 - val_accuracy: 0.7704 - val_loss: 0.4787
Epoch 2/5
196/196 ━━━━━━━━━━━━━━━━━━━━ 7s 12ms/step - accuracy: 0.8040 - loss: 0.4376 - val_accuracy: 0.7962 - val_loss: 0.4406
Epoch 3/5
196/196 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.8523 - loss: 0.3469 - val_accuracy: 0.8102 - val_loss: 0.4121
Epoch 4/5
196/196 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.8750 - loss: 0.3071 - val_accuracy: 0.8032 - val_loss: 0.4390
Epoch 5/5
196/196 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - accuracy: 0.8905 - loss: 0.2702 - val_accuracy: 0.8028 - val_loss: 0.4441


In [13]:
test_data = X_test[0][0:50].reshape(1,-1)

In [16]:
model.predict(test_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step


array([[0.2047944]], dtype=float32)